version: "3.3"

services:
  snikket:
    image: snikket:latest
    network_mode: host
    volumes:
      - type: "volume"
        source: snikket_data
        target: /snikket
    env_file: snikket.conf
    restart: "unless-stopped"

volumes:
  snikket_data:
