---

- name: "Install supervisord"
  apt:
    name: supervisor
    state: present
    install_recommends: no
- name: "Deploy supervisor config"
  copy:
    src: "../files/supervisord.conf"
    dest: "/etc/supervisor/conf.d/supervisord.conf"
